stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  DOCKER_REGISTRY: 555726879390.dkr.ecr.us-east-1.amazonaws.com
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: clarusway-repo/petclinic-app-dev
  DOCKER_HOST: tcp://docker:2375

build_react_image:
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  stage: build

  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
    - pwd && ls -ltar && df -h
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID . 
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
  rules:
    - if: ($CI_COMMIT_BRANCH == "dev") && ($CI_PIPELINE_SOURCE == "schedule")
      changes:
      - src/*


build_terraform_env:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - yum install -y yum-utils
    - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    - yum -y install terraform
    - aws --version
    - docker --version
    - terraform --version
    - pwd && ls -ltar && df -h
  script:
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws s3 ls
  allow_failure: false
  
  rules:
   - if: ($CI_COMMIT_BRANCH == "dev")
     when: always
   - when: never

  cache:
    key: $CI_COMMIT_REF_SLUG
