concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "ip-172-31-83-149"
  url = "https://gitlab.com/"
  token = "***"  # Enter your token from Gitlab > Your Project > Settings > CI/CD > Runners > Spesific Runner
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "amazon/aws-cli"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
root@ip-172-31-83-149:/home/ubuntu#
