---
apiVersion: v1
kind: Service
metadata:
  namespace: stage
  labels:
    app: react-app
  name: react-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react-app